project:
  type: website
  output-dir: docs
  resources: 
    - "*.html"
    - "*.js"
    - "*.p8.png"

website:
  title: "p8games"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



