project:
  type: website
  resources: 
    - "resources/*"

website:
  title: "p8games"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



